apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: slamidtfyn/microserviceapp
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://::5010"